name: "Easywave2MQTT"
description: "Support Easywave devices in Home Assistant using MQTT"
version: "0.2.0"
url: "https://github.com/marcselis/Easywave2MQTT"
slug: "easywave2mqtt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /dev/ttyUSB0
